# Generated by Django 2.2.4 on 2019-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Desc',
            field=models.TextField(default=()),
            preserve_default=False,
        ),
    ]
