# Generated by Django 2.2.4 on 2019-08-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20190826_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
