# Generated by Django 2.2.4 on 2019-08-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='users',
            new_name='user',
        ),
    ]
